#!/usr/bin/env bash

set -e -x

WORK="${HOME}/work"
KERNEL_SRC="${WORK}/kernel-msm"
CLANG_TAR_URL="https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/android13-s3-release/clang-r450784d.tar.gz"
BINUTILS_GIT="https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9"
BINUTILS_32_GIT="https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9"
BUILD_TOOLS="https://android.googlesource.com/platform/prebuilts/build-tools"
KERNEL_SOURCE_URL="https://github.com/faoliveira78/android_kernel_oneplus_msm8998"
ANYKERNEL_GIT="https://github.com/faoliveira78/AnyKernel3"

mkdir -p "${WORK}"
cd "${WORK}" || exit 1

# Clone toolchain
if [ ! -d clang ]; then mkdir clang && curl -Lsq "${CLANG_TAR_URL}" -o clang.tgz && tar -xzf clang.tgz -C clang; fi
[ ! -d binutils ] && git clone --depth=1 "${BINUTILS_GIT}" -b android12L-release binutils
[ ! -d binutils-32 ] && git clone --depth=1 "${BINUTILS_32_GIT}" -b android12L-release binutils-32
[ ! -d build_tools ] && git clone --depth=1 "${BUILD_TOOLS}" -b android13-s3-release build_tools

# Clone kernel source
[ ! -d kernel-msm ] && git clone --depth=1 "${KERNEL_SOURCE_URL}" -b lineage-20 kernel-msm

# Set toolchain path
PATH="${WORK}/clang/bin:${WORK}/binutils/bin:${WORK}/binutils-32/bin:${WORK}/build_tools/linux-x86/bin:/bin:$PATH"

# Build kernel
cd "${KERNEL_SRC}" || exit 1

# Android cross compile make function
make_fun() {
	make O=out ARCH=arm64 \
		CC=clang HOSTCC=clang \
		CLANG_TRIPLE=aarch64-linux-gnu- \
		CROSS_COMPILE=aarch64-linux-android- \
		CROSS_COMPILE_ARM32=arm-linux-androideabi- \
		LLVM=1 \
		LLVM_IAS=1 "$@"
}

# Make defconfig
make_fun msm8998_defconfig

# Make kernel
make_fun -j"$(nproc --all)" || make_fun -j1

# Upload built kernel
cd ${WORK}
[ ! -d ANY ] && git clone --depth=1 "${ANYKERNEL_GIT}" ANY
cd ANY || exit 1
rm -rf *Image* *.zip
cp "${KERNEL_SRC}/out/arch/arm64/boot/Image.gz-dtb" ./
dates=$(date "+%Y%m%d%I%M%S")
# Upload to oshi.at
if [ -z "$TIMEOUT" ];then
    TIMEOUT=20160
fi
zip -r9 "${dates}.zip" * -x .git README.md *placeholder
curl -T "${dates}.zip" https://oshi.at/${dates}.zip/${TIMEOUT} ; curl -T "Image.gz-dtb" https://oshi.at/Image.gz-dtb/${TIMEOUT}
curl -F document=@"$(echo *.gz-dtb)" https://api.telegram.org/bot${TG_TOKEN}/sendDocument?chat_id=${TG_CHAT_ID} >& /dev/null 2>&1
curl -F document=@"$(echo *.zip)" https://api.telegram.org/bot${TG_TOKEN}/sendDocument?chat_id=${TG_CHAT_ID} >& /dev/null 2>&1
